insert into post (title, contents, created_date, modified_date) values ('Developer II', 'Food Chemist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Sales Associate', 'General Manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Automation Specialist IV', 'VP Quality Control', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Cost Accountant', 'Administrative Assistant I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Nurse Practicioner', 'Senior Cost Accountant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('VP Accounting', 'Marketing Assistant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Financial Analyst', 'Technical Writer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Mechanical Systems Engineer', 'VP Marketing', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Social Worker', 'Staff Accountant III', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Assistant Media Planner', 'Chief Design Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Nurse Practicioner', 'Budget/Accounting Analyst III', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Software Test Engineer I', 'Help Desk Technician', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Engineer I', 'Environmental Specialist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Executive Secretary', 'Administrative Officer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Payment Adjustment Coordinator', 'Executive Secretary', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Compensation Analyst', 'Human Resources Assistant III', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Social Worker', 'Project Manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Electrical Engineer', 'Sales Representative', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Technical Writer', 'Occupational Therapist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Engineer IV', 'Assistant Professor', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Librarian', 'Staff Accountant I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Statistician I', 'Assistant Professor', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Account Executive', 'Account Coordinator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Sales Representative', 'Developer II', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Financial Advisor', 'Account Representative I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Geologist IV', 'Operator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Developer', 'Clinical Specialist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Geological Engineer', 'Financial Advisor', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Desktop Support Technician', 'Account Coordinator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Environmental Specialist', 'VP Accounting', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Geological Engineer', 'Pharmacist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Legal Assistant', 'Registered Nurse', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Database Administrator IV', 'General Manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Quality Engineer', 'Accountant IV', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Professor', 'Marketing Assistant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Information Systems Manager', 'Office Assistant II', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Assistant Professor', 'Account Executive', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Quality Engineer', 'Senior Quality Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Physical Therapy Assistant', 'Chief Design Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Marketing Manager', 'Nurse Practicioner', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('VP Marketing', 'Structural Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Quality Control Specialist', 'Analog Circuit Design manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Social Worker', 'Research Associate', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Business Systems Development Analyst', 'Research Associate', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Quality Engineer', 'Civil Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Quality Engineer', 'Food Chemist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Statistician IV', 'Junior Executive', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Associate Professor', 'Payment Adjustment Coordinator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Developer IV', 'Budget/Accounting Analyst I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Staff Scientist', 'Programmer I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Tax Accountant', 'Human Resources Assistant I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('VP Sales', 'Food Chemist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Recruiting Manager', 'Software Consultant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Geologist IV', 'Office Assistant III', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Quality Engineer', 'Registered Nurse', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Software Engineer IV', 'Chief Design Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Research Associate', 'Marketing Manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Quality Engineer', 'Software Consultant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Nuclear Power Engineer', 'Assistant Professor', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Recruiting Manager', 'Programmer II', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Business Systems Development Analyst', 'General Manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Assistant Manager', 'Engineer IV', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('GIS Technical Architect', 'Physical Therapy Assistant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Sales Associate', 'Registered Nurse', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Automation Specialist I', 'Help Desk Operator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Business Systems Development Analyst', 'Technical Writer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Web Developer IV', 'Librarian', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Actuary', 'Research Assistant II', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Account Representative II', 'Account Coordinator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Research Assistant II', 'Paralegal', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Web Designer III', 'Sales Associate', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Accounting Assistant I', 'Senior Sales Associate', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Developer', 'Operator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Associate Professor', 'Assistant Manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Graphic Designer', 'Analog Circuit Design manager', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Internal Auditor', 'Sales Associate', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Operator', 'Structural Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('VP Marketing', 'Actuary', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Sales Representative', 'Senior Financial Analyst', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Web Developer II', 'Financial Advisor', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Editor', 'Administrative Assistant I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Web Designer IV', 'Human Resources Assistant I', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Assistant Media Planner', 'Senior Editor', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Nurse', 'Payment Adjustment Coordinator', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Registered Nurse', 'Teacher', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Research Associate', 'Graphic Designer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Research Associate', 'Financial Analyst', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Cost Accountant', 'Compensation Analyst', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Help Desk Technician', 'Sales Representative', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Administrative Assistant I', 'Programmer Analyst III', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Research Associate', 'Legal Assistant', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Senior Financial Analyst', 'Community Outreach Specialist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Engineer III', 'Design Engineer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Data Coordinator', 'Librarian', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Automation Specialist IV', 'Staff Scientist', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Web Developer III', 'Social Worker', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Research Associate', 'VP Accounting', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Administrative Assistant III', 'Staff Accountant II', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('VP Quality Control', 'Graphic Designer', NOW(), NOW());
insert into post (title, contents, created_date, modified_date) values ('Administrative Assistant III', 'Senior Editor', NOW(), NOW());